// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package ipinfotest contains autogenerated mocks.
package ipinfotest

import "github.com/johnstcn/freshcomics/internal/ipinfo"
import "github.com/stretchr/testify/mock"
import "net"

// IPInfoer is an autogenerated mock type for the IPInfoer type
type IPInfoer struct {
	mock.Mock
}

// GetIPInfo provides a mock function with given fields: addr
func (mockerySelf *IPInfoer) GetIPInfo(addr net.IP) (ipinfo.GeoLoc, error) {
	ret := mockerySelf.Called(addr)

	var r0 ipinfo.GeoLoc
	if rf, ok := ret.Get(0).(func(net.IP) ipinfo.GeoLoc); ok {
		r0 = rf(addr)
	} else {
		r0 = ret.Get(0).(ipinfo.GeoLoc)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(net.IP) error); ok {
		r1 = rf(addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
