version: '3'
services:
  frontend:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: johnstcn/freshcomics-frontend:latest
    depends_on:
      - db
    networks:
      - freshcomics-network

  crawler:
    ports:
      - "8001:8001"
    build:
      context: .
      dockerfile: Dockerfile.crawler
    image: johnstcn/freshcomics-crawler:latest
    depends_on:
      - db
    networks:
      - freshcomics-network

  db:
    image: postgres:9.4
    ports:
      - "5432"
    restart: always
    networks:
      - freshcomics-network
    environment:
      - POSTGRES_USER=freshcomics
      - POSTGRES_PASSWORD=freshcomics_password
      - POSTGRES_DB=freshcomicsdb

networks:
  freshcomics-network: