// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	store "github.com/johnstcn/freshcomics/internal/store"
	mock "github.com/stretchr/testify/mock"
)

// ComicStore is an autogenerated mock type for the ComicStore type
type ComicStore struct {
	mock.Mock
}

// GetComics provides a mock function with given fields:
func (_m *ComicStore) GetComics() ([]store.Comic, error) {
	ret := _m.Called()

	var r0 []store.Comic
	if rf, ok := ret.Get(0).(func() []store.Comic); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Comic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
