---
  - name: build executable locally
    delegate_to: localhost
    shell: CGO_ENABLED=0 go build -ldflags="-s -w" freshcomics-crawler.go
    args:
      chdir: ../../crawler
    tags:
      - provision
      - deploy

  - name: copy binary to destination
    copy:
      src: ../../crawler/freshcomics-crawler
      dest: "{{ freshcomics_home }}/freshcomics-crawler"
      owner: "{{ freshcomics_user }}"
      group: "{{ freshcomics_group }}"
      mode: 0744
    become: yes
    notify: restart freshcomics-crawler
    tags:
      - provision
      - deploy

  - name: ensure systemd service file is present for freshcomics-crawler
    template:
      src: freshcomics-crawler.service.j2
      dest: /etc/systemd/system/freshcomics-crawler.service
      owner: root
      group: root
      mode: 0640
    become: yes
    notify: restart freshcomics-crawler
    tags:
      - provision

  - name: ensure env file is present for freshcomics-crawler
    template:
      src: freshcomics-crawler.env.j2
      dest: /opt/freshcomics/freshcomics-crawler.env
      owner: root
      group: root
      mode: 0640
    become: yes
    notify: restart freshcomics-crawler
    tags:
      - provision

  - name: ensure freshcomics-crawler service is enabled
    systemd:
      name: freshcomics-crawler.service
      enabled: yes
      masked: no
      daemon_reload: yes
    become: yes
    notify: restart freshcomics-crawler
    tags:
      - provision

  - name: ensure nginx config is present for freshcomics-crawler
    template:
      src: freshcomics-crawler.conf.j2
      dest: /etc/nginx/conf.d/freshcomics-crawler.conf
      owner: root
      group: root
    become: yes
    notify: restart nginx
    tags:
      - provision

  - name: ensure nginx htpasswd file is present for freshcomics-crawler
    htpasswd:
      path: /etc/nginx/freshcomics-crawler.htpasswd
      name: "{{ freshcomics_crawler_admin_user }}"
      password: "{{ freshcomics_crawler_admin_password }}"
      owner: root
      group: nginx
      mode: 0640
    notify: restart nginx
    become: yes
    tags:
      - provision

...